# Generated by Django 6.0 on 2025-12-31 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
