# Generated by Django 6.0 on 2026-01-01 12:23

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_universe_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'New play session')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.universe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('stage__in', [0])), name='api_PlaySession_stage_PlaySessionStageEnum')],
            },
        ),
    ]
