# Generated by Django 5.1.5 on 2026-01-18 09:52

import django.db.models.deletion
import django_enum.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_playsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hull',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('hull_size', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Extra Small'), (1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('hull_class', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Admiral'), (1, 'Transport'), (2, 'Explorer')])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('hull_size__in', [0, 1, 2, 3])), name='api_Hull_hull_size_HullSizeEnum'), models.CheckConstraint(condition=models.Q(('hull_class__in', [0, 1, 2])), name='api_Hull_hull_class_HullClassEnum')],
            },
        ),
        migrations.CreateModel(
            name='HullSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hull_size', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Extra Small'), (1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hull')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('hull_size__in', [0, 1, 2, 3])), name='api_HullSlot_hull_size_HullSizeEnum')],
            },
        ),
    ]
