# Generated by Django 6.0 on 2026-02-11 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hull_hullslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='hullslot',
            name='installed_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehiclemodule'),
        ),
    ]
