# Generated by Django 6.0 on 2026-02-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hullslot_installed_module'),
        ('api', '0007_vehiclemodule_hullslot_installed_module'),
    ]

    operations = [
    ]
