# Generated by Django 6.0 on 2026-02-20 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20260220_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Vaisseau Amiral', max_length=200)),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hull')),
            ],
        ),
        migrations.AddField(
            model_name='playsession',
            name='starship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.starship'),
        ),
    ]
